# -*- coding: utf-8 -*-
"""IRIS CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8b6yg6Sj4MPj_bp59Z5WGDWS92UFjjY
"""

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_iris

iris = load_iris()

# Convert the dataset into a pandas DataFrame for easier analysis
iris_data = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_data['Species'] = iris.target

# Replace numeric species labels with the actual names
species_map = {0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'}
iris_data['Species'] = iris_data['Species'].map(species_map)

print("First few rows of the dataset:")
print(iris_data.head())

# EDA: Pairplot to visualize features
sns.pairplot(data, hue='Species')
plt.show()

X = iris_data[iris.feature_names]
y = iris_data['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nTraining the Random Forest Classifier...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

#Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy of the model: {accuracy:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
species_names = list(species_map.values())
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=species_names, yticklabels=species_names)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()